language: ruby

rvm:
  - 2.4.3

# sudo: enabled

services:
  - postgresql

branches:
  only:
  - develop

# env:
# - DB=mongodb 

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database auto_deploy_test;' -U postgres

before_install:
  # - sudo apt-get -qq update

install:
  - bundle install


script:
  # - bundle exec rake ci:tests    



notifications:
  email:
    recipients:
      - pradeep@mashey.com
      - vel@mashey.com
    on_success: never # default: change
    on_failure: always # default: always
  # slack:
  #   rooms:
  #     - <account>:<token>#development
  #   on_success: change # default: always
  #   on_failure: always # default: always


# branches:  
#   except: 
#     - master

# install:
#   - bundle install


# before_script:
#   # - bundle exec rake db:test:prepare
#   # - bundle exec rake db:migrate
# script:
#   # - bundle exec rake ci:tests
# services:
#   - postgresql
# notifications:
#   email: true