language: ruby
rvm:
  - 2.4.3

before_script:
  # - bundle exec rake db:test:prepare
  # - bundle exec rake db:migrate
script:
  - bundle exec rake ci:tests
services:
  - postgresql
notifications:
  email: true